name: Create release Tags
on: workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Ec-tests-stack to run the smoke tests
        uses: actions/checkout@v2
        with:
          repository: cebroker/ec-tests-stack
          token: ${{ secrets.CICD_PAT }}
          path: ec-tests-stack
      - name: Set up node environment
        uses: actions/setup-node@v2
        with:
          node-version: '13.8.0'
      - name: Test everything so far is working
        run: |
          node -v
          pwd
