name: Create release Tags
on:
  workflow_dispatch:
    inputs:
      smoke-test-command:
        description: 'Smoke test command to test this repository'
        required: true
        default: ''

jobs:
  env-variables:
    runs-on: ubuntu-latest
    outputs:
      smoke-test-command:
        description: 'Specific smoke test command to execute'
        value: ${{ steps.set-vars.outputs.smoke-test-command }}
    steps:
      - name: Set variables
        id: set-vars
        run: |
          echo "::set-output name=smoke-test-command:: ${{ github.event.inputs.smoke-test-command }}"

  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Ec-tests-stack to run the smoke tests
        uses: actions/checkout@v2
        with:
          repository: cebroker/ec-tests-stack
          token: ${{ secrets.CICD_PAT }}
          path: ec-tests-stack
      - name: Set up node environment
        uses: actions/setup-node@v2
        with:
          node-version: '13.8.0'
      - name: Test everything so far is working
        run: |
          node -v
          pwd
